# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec app.yaml

name: dealflow-analytics
region: nyc

services:
  - name: api
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/dealflow-analytics
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xs  # $5/month (512MB RAM, 1 vCPU)
    # For production use: basic-s ($12/month, 1GB RAM, 1 vCPU)
    
    # HTTP configuration
    http_port: 8000
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    # Routes
    routes:
      - path: /
    
    # Environment variables (these will be encrypted)
    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${ANTHROPIC_API_KEY}
      
      - key: GITHUB_TOKEN
        scope: RUN_TIME
        type: SECRET
        value: ${GITHUB_TOKEN}
      
      - key: NEWS_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${NEWS_API_KEY}
      
      - key: REDIS_HOST
        scope: RUN_TIME
        value: ${redis.HOSTNAME}
      
      - key: REDIS_PORT
        scope: RUN_TIME
        value: ${redis.PORT}
      
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${db.DATABASE_URL}
      
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"
      
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "INFO"
    
    # CORS configuration for Chrome extension
    cors:
      allow_origins:
        - prefix: chrome-extension://
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization

# Database (PostgreSQL)
databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database  # $7/month (1GB RAM, 10GB disk)
    # For production use: db-s-1vcpu-1gb ($15/month)
    num_nodes: 1

# Redis for caching
# Note: DigitalOcean doesn't have managed Redis yet, 
# so we'll use an in-memory cache in the app for now
# or deploy Redis as a separate service

# Alternative: Add Redis as a service
# services:
#   - name: redis
#     dockerfile_path: redis/Dockerfile
#     source_dir: redis
#     instance_count: 1
#     instance_size_slug: basic-xxs
#     internal_ports:
#       - 6379

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES

# For custom domain (add after deployment)
# domains:
#   - domain: api.dealflow.com
#     type: PRIMARY
#     zone: dealflow.com