# DigitalOcean App Platform Specification
# Deploy with: doctl apps update YOUR_APP_ID --spec app.yaml

name: monkfish-app
region: fra

services:
  - name: dealflow-analytics
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: Strategyherogo/dealflow-analytics
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Current configuration
    
    # HTTP configuration
    http_port: 8080
    
    # Environment variables
    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:l113GEkVv8D1yiv58qpVRGIza4Ko5EkE:AjDyPm9Q/Ob+gC8n4Wc60c8X+ZzePuEiRiz1A7rO0VGrwQTOji3rD/7bKFgk05o92SnaexnamSnu8I3v3hkO6z+q2Cwqn91+r/E8NKLE7knFgqZJNZyiD81LaoHLNK706fLdmCupn8pUeBNokTQN8kJ2Do+gygMsxBg2cQ==]
      
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: sk_test_placeholder_key
      
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
        value: whsec_placeholder_secret
      
      - key: STRIPE_PRO_PRICE_ID
        scope: RUN_TIME
        value: price_pro_monthly
      
      - key: STRIPE_PREMIUM_PRICE_ID
        scope: RUN_TIME
        value: price_premium_monthly
      
      - key: STRIPE_ENTERPRISE_PRICE_ID
        scope: RUN_TIME
        value: price_enterprise_monthly
      
      - key: STRIPE_TEST_MODE
        scope: RUN_TIME
        value: "true"
      
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: your-jwt-secret-key-here
      
      - key: PYTHONUNBUFFERED
        scope: RUN_TIME
        value: "1"
      
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "INFO"

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# Features
features:
  - buildpack-stack=ubuntu-22

# Ingress configuration
ingress:
  rules:
    - component:
        name: dealflow-analytics
      match:
        authority: {}
        path:
          prefix: /