version: '3.8'

services:
  dealflow-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=postgresql://dealflow:${DB_PASSWORD}@postgres:5432/dealflow
    depends_on:
      - redis
      - postgres
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dealflow-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - dealflow-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=dealflow
      - POSTGRES_USER=dealflow
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - dealflow-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - dealflow-api
    restart: unless-stopped
    networks:
      - dealflow-network

volumes:
  redis_data:
  postgres_data:

networks:
  dealflow-network:
    driver: bridge